services:
  stats-server:
    environment:
      - SPRING_PROFILES_ACTIVE=production
    build:
      context: ./
      dockerfile: stats-service/stats-server/Dockerfile
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    ports:
      - "5433:5432"

  ewm-service:
    environment:
      - SPRING_PROFILES_ACTIVE=production
    build:
      context: ./
      dockerfile: ewm-service/Dockerfile
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
